### ISSUE TITLE
new vaccine Janssen causes problem in vaccinated calculations

### ISSUE THREAD

**Issue by chrispfau** [ThisIsBenny/rki-vaccination-data#35] opened 2021-04-27 10:04 UTC
**Hi ThisIsBenny**,
Thank You for your great work! I recognized a problems in the calculations of the value of "vaccinated" due to a newly added vaccine "Janssen". The value sums row[2] + row[12] and the new column Janssen should lead to row[2] + row[13]. Same for the values of "vaccinated_by_accine". It's just a small thing, which leads to wrong data from today on. [edit:] it is in the file "_utils/scrap_data.py"

greez 

chrispfau

**Comment by Viet2503** [comment] 2021-04-27 11:44
I just wrote a fix.
As @chrispfau stated, the new RKI sheet now contains a new col for the Janssen vaccine.

Which basically means every row[x] for x >= 11 needs to be set to row[x+1]. 
And data scraping for new janssen vaccination has to be added in the second vaccination section. 

See PR #36.

**Comment by ThisIsBenny** [comment] 2021-04-27 18:11
Hi @chrispfau
Hi @Viet2503, thanks for the PR. I will accept the PR now.

But i see now an issue with the current implementation.
I use the First Vaccination to calculate the quote. After the first vaccination you are already protected a bit and the numbers give you more hope :-D
However, Janssen counts in the column "Fully vaccinated".
any suggestions on how to deal with this now?

**Comment by Viet2503** [comment] 2021-04-27 18:19
Haha well, I thought of that problem as well, but didn't come up with a solution. 

Maybe count the Janssen vaccinations as "First vaccinated" and "Fully vaccinated"?
So a shot with Janssen will increase the "First vaccinated" quota and the "Fully vaccianted" quota.

**Comment by ThisIsBenny** [comment] 2021-04-27 18:25
@Viet2503 i have also thought about this. But I'm not sure if everyone will like this. I use the API only for my scriptable widget, but there a also some other developers which are using this API.
Maybe i will provide a new V2 API where i can solve some issues which i have seen in the last time. The problem was that the RKI changed a lot in the sheet so the Response is in my eyes very ugly, because i try to keep the base structure stable, so that i didn't have breaking changes. 
In case that i develop a second v2 API, i can migrate my script to this one and add a support for first vaccination and fully vaccinated.
the v1 API will then only be maintained like "still working" but i will not add new fields or something.

**Comment by Viet2503** [comment] 2021-04-27 18:28
That sounds like a possible solution.
In case you write a v2 API, consider this: [https://impfdashboard.de/daten](https://impfdashboard.de/daten)
The Bundesministerium für Gesundheit now provides .tsv files which can be parsed easier than the excel sheet. 

But I guess, they just parse the RKI sheet as well.

**Comment by TheSpirit** [comment] 2021-04-27 18:28
There seems to be still an issue. If I add difference_to _the_prevoius_day for first an second vaccination for Germany I get a different value checking against the value listed on the last page of the excel sheet. Can you please check this?
Thanks

**Comment by Viet2503** [comment] 2021-04-27 18:48
I think this is probably because of missing numbers for "Impfzentrum Bund". 
@TheSpirit

**Comment by ThisIsBenny** [comment] 2021-04-27 18:58
@Viet2503 correct. "Impfzentrum Bund" is not in the list of states, why the numbers are ignored.
The problem is that there are no "inhabitants" for "Impfzentrum Bund", why i have to adjust a little bit the logic.
And i'm also thinking about if i should return "Impfzentrum Bund" as part of the state list or if i only use the numbers for calculating the totals.

**Comment by TheSpirit** [comment] 2021-04-29 09:11
i would only use the numbers of "Impfzentrum Bund" for calculating the totals

**Comment by therealrandallflagg** [comment] 2021-05-03 11:41
There is also now a new column "Janssen" for "niedergelassene Ärzte".

**Comment by ThisIsBenny** [comment] 2021-05-03 16:01
> There is also now a new column "Janssen" for "niedergelassene Ärzte".

Will be fixed with #37

Before I merge it, I will add a support for "Impfzentrum Bund"

**Comment by ThisIsBenny** [comment] 2021-05-03 16:43
Done ✅

**Closed as completed by ThisIsBenny** 2021-05-03 16:43 UTC
